version = "0.1.0"

[[files]]
  file = "version.txt"
  expr = "(.+?)$"

[[files]]
  file = "lib/utils.bash"
  expr = 'POLYGLOT_VERSION="(.+?)"$'

[[files]]
  file = "polyglot/polyglot"
  expr = 'POLYGLOT_VERSION="(.+?)"$'

[package]
